@startuml uc02
title "Use Case #2: User Login"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom
skinparam sequenceMessageAlign direction
skinparam sequence {
    LifeLineBorderColor #Silver
    LifeLineBackgroundColor #Gainsboro
}

'Setup the objects involved here
actor User as u <<Actor>>
boundary App as a <<Boundary>>
boundary LoginWindow as lw <<Boundary>>
control LoginRoute as lr <<Control>>
control DatabaseManager as db <<Control>>
boundary DeviceStorage as ds <<Boundary>>

'Setup persistent objects here
activate u 
activate a
activate lr
activate db
activate ds

'--- FLOW OF CONTROL STARTS HERE ---
'User selects “Login” on the front page.
u -> a: Selects “Login” \nin the welcome window

'System shows a form to Login
a -> lw: show()
activate lw

=="Use Case #5: Decrypt Vault" is called to decrypt the vault==

lw -> lr: POST /api/users/login json::user_info

=="Use Case 8: Challenge User" is called to verify the identity of the user==

'Server issues a token and returns to user for confirmation
lr -> db: issueToken()
lr -> u: Return token to user, confirming the success of the login
lr -> ds: Persist the token in local storage

'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
