@startuml uc01
title "Use Case #6: Delete Account"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom
skinparam sequenceMessageAlign direction
skinparam sequence {
	LifeLineBorderColor #Silver
	LifeLineBackgroundColor #Gainsboro
}


'Setup the objects'
actor User as u <<Actor>>
boundary App as a <<Boundary>>
boundary UserSettingScreen as uss <<Boundary>>
control DatabaseManager as dm <<Control>>
boundary Database as db <<Boundary>>

'Setup persistent objects here'
activate u
activate a

'--- FLOW OF CONTROL STARTS HERE ---'

'User navigates to the "User settings page"'
u -> a: <user navigates to the User Settings page>
a -> uss: show()
activate uss

'User clicks "Delete Account" button'
u -> uss: <user clicks "Delete Account" button>

'Users device sends a deletion request to the server'
uss -> dm: User sends a deletion request to the server
activate dm


'Server challenges user to verify the authenticity of the user'
dm -> u: server challenges user to verify authenticity and sends email containing confirmation link to confirm deletion

'User recieves the email and clicks the link to finish the process of deleting account
u -> dm: User uses email link to confirm deletion of their account

'Database manager marks the account for deletion and sends the user a notification via email
dm -> db: Database manager marks account in the database for deletion
activate db

'Database manager sends notification email once account is marked for deletion
dm -> u: Database manager sends notification abount successful deletion mark



@enduml