@startuml uc01
title "Use Case #1: Create Account"


'Styling goes here
hide footbox
skinparam stereotypePosition bottom
skinparam sequenceMessageAlign direction
skinparam sequence {
	LifeLineBorderColor #Silver
	LifeLineBackgroundColor #Gainsboro
}

'Setup the objects involved here
actor User as u <<Actor>>
boundary App as a <<Boundary>>
entity Vault as v <<Entity>>
boundary RegistrationWindow as rw <<boundary>>
control RegisterUserRoute as rur <<Control>>
control DatabaseManager as db <<Control>> 

'Setup persistent objects here
activate u 
activate a
activate rur
activate db


'--- FLOW OF CONTROL STARTS HERE ---
' User selects “Create Account” on the front page.
u -> a: Selects “Create Account”

' System shows a form to create the account.
activate rw
a -> rw: showWindow()

' User enters email address, username and click "Create account"
u -> rw: Enters email, username and clicks "Create account"

' User device send a request to the server to create an account
rw -> rur: POST /users/register

rur -> db: QUERY ensureNonexistantUser(userCollection, username)

alt User already exists
	db --> rur: return: err
	db --> rw: RESP json::{"status": "error", "message": "User already exists"}
else User does not exist
	db --> rur: 
	rur --> rw: RESP json::{"status": "success", "message": "Account created successfully, please verify email"}
end
deactivate rw

rur -> db: QUERY createAccount(email, username)
rur -> u: Create challenge and send to user email
u -> rur: User verify email and enter challenge
rur --> a: RESP json::{"status": "success", "message": "Successfully verified email"}

'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
