@startuml uc09
title "Use Case #9: Generate Passphrase"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom

'Setup the objects involved here

'Setup persistent objects here

'--- FLOW OF CONTROL STARTS HERE ---
'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
