@startuml uc05
title "Use Case #5: Decrypt Vault"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom
skinparam sequenceMessageAlign direction
skinparam sequence {
	LifeLineBorderColor #Silver
	LifeLineBackgroundColor #Gainsboro
}

'Setup the objects involved here

'Setup persistent objects here

'--- FLOW OF CONTROL STARTS HERE ---
'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
