@startuml uc01
title "Use Case #1: Create Account"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom

'Setup the objects involved here

'Setup persistent objects here

'--- FLOW OF CONTROL STARTS HERE ---
'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
