@startuml uc11
title "Use Case #11: Leave Conversation"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom
skinparam sequenceMessageAlign direction
skinparam sequence {
	LifeLineBorderColor #Silver
	LifeLineBackgroundColor #Gainsboro
}

'Add a legend plus styling
skinparam legend {
	backgroundColor #GhostWhite
	entrySeparator #GhostWhite
}

legend top
	<#GhostWhite,#GhostWhite>|	|= __Legend__ |
	|<#red> | Clientside|
	|<#silver> | Serverside|
endlegend

'Setup the objects involved here
Actor User as u <<Actor>> #red
boundary App as a <<Boundary>> #red
boundary ConversationWindow as cw <<Boundary>> #red
control ConversationManager as cm <<Control>> #red
control VaultManager as vm <<Control>> #red
control WSHandler as ws <<Control>> #silver

'Setup persistent objects here
activate u
activate a
activate cw
activate cm
activate vm
activate ws

'--- FLOW OF CONTROL STARTS HERE ---
'User select the option to leave the chat room or they leave the app.
u -> a: Navigates away from the\n current conversation window
a -> cw: destroy()
cw -> cm: cleanup(savedMessages)
cm -> ws: disconnect(user.id, convo.id)
deactivate cw

'User’s device persists saved chats to the vault.
cm -> vm: saveMessages(cid, savedMessages)

'User’s device saves the chat session to their vault.
cm -> vm: saveSession(cid, session)

'Unsaved messages are destroyed and zeroed out to avoid leakage of confidential details
cm -> cm: eraseUnsavedMessages()

== "Use Case #7: Encrypt Vault" is called to save the vault to local storage ==

'User’s device displays the chats list page. This step is skipped if the user left the app or sent it to the background.
a -> u: show chats list page, if still in focus
'--- FLOW OF CONTROL ENDS HERE   ---

@enduml