@startuml uc16
title "Use Case #16: Receive Message"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom
skinparam sequenceMessageAlign direction
skinparam sequence {
	LifeLineBorderColor #Silver
	LifeLineBackgroundColor #Gainsboro
}

'Setup the objects involved here
actor User as u <<Actor>>
boundary UserDevice as ud <<Boundary>>
boundary App as a <<Boundary>>
boundary ChatRoomScreen as crs <<Boundary>>
control GetMessageRoute as gmr <<Control>>
control ReceiveQueue as rq <<Control>>

'Setup persistent objects here
activate u
activate ud
activate a
activate gmr
activate rq

'--- FLOW OF CONTROL STARTS HERE ---
a -> gmr: make request for unread message
gmr -> rq: get messages from queue
rq --> gmr: return messages
gmr --> a: RESP /api/send_message json: {sending_user, message}
a -> a: decrypt messages
'not sure if this is correct:
a -> a: update ratchet state 

group If User is Offline
  a -> ud: Send push notification
end

u -> a: open message
a -> crs: display message
activate crs
u -> crs: user read message
crs -> a: mark message as read
a -> gmr: make request to remove message from queue
gmr -> rq: remove message from queue





'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
