@startuml uc13
title "Use Case #13: Check Key Revocation"

'Styling goes here
hide footbox
skinparam stereotypePosition bottom

'Setup the objects involved here

'Setup persistent objects here

'--- FLOW OF CONTROL STARTS HERE ---
'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
