@startuml uc03
title Use Case #3: Create Conversation
hide footbox

'Setup the objects involved here

'Setup persistent objects here

'--- FLOW OF CONTROL STARTS HERE ---
'--- FLOW OF CONTROL ENDS HERE   ---

@enduml
